"""empty message

Revision ID: 3e7face35638
Revises: e8f7da151d15
Create Date: 2017-04-26 02:22:03.258321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7face35638'
down_revision = 'e8f7da151d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_tokens', sa.Column('agent', sa.String(), nullable=True))
    op.add_column('auth_tokens', sa.Column('last_ip', sa.String(), nullable=True))
    op.add_column('auth_tokens', sa.Column('last_used', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_tokens', 'last_used')
    op.drop_column('auth_tokens', 'last_ip')
    op.drop_column('auth_tokens', 'agent')
    # ### end Alembic commands ###
